// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBgl3IQwhXXwQ4372GbUzu2lf4YrQQXMU',
    appId: '1:395311090803:web:b7575978cd61839dc52e06',
    messagingSenderId: '395311090803',
    projectId: 'kyradi',
    authDomain: 'kyradi.firebaseapp.com',
    storageBucket: 'kyradi.firebasestorage.app',
    measurementId: 'G-PFDWSD4XKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK38k_MWSMFRl8uOp-iT3kTZiwdFLKAs8',
    appId: '1:395311090803:android:4c33dfbeff0b0028c52e06',
    messagingSenderId: '395311090803',
    projectId: 'kyradi',
    storageBucket: 'kyradi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHYbgzeqa_H82T2JaGsDn0vvbdMrXKsTc',
    appId: '1:395311090803:ios:1cc00f9d466c3628c52e06',
    messagingSenderId: '395311090803',
    projectId: 'kyradi',
    storageBucket: 'kyradi.firebasestorage.app',
    iosBundleId: 'com.dilan.bavulgooappp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHYbgzeqa_H82T2JaGsDn0vvbdMrXKsTc',
    appId: '1:395311090803:ios:de8f712cac0cbfbbc52e06',
    messagingSenderId: '395311090803',
    projectId: 'kyradi',
    storageBucket: 'kyradi.firebasestorage.app',
    iosBundleId: 'com.example.bavulgoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBgl3IQwhXXwQ4372GbUzu2lf4YrQQXMU',
    appId: '1:395311090803:web:e77c3f4b6c2b8604c52e06',
    messagingSenderId: '395311090803',
    projectId: 'kyradi',
    authDomain: 'kyradi.firebaseapp.com',
    storageBucket: 'kyradi.firebasestorage.app',
    measurementId: 'G-BPDKFM5QE7',
  );
}
