// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2dUY0t2cGXdV7N0CJowNN4OA-nMwfw-Q',
    appId: '1:143197560587:web:7b5a3069f93671f2108c0e',
    messagingSenderId: '143197560587',
    projectId: 'kyradi-superapp',
    authDomain: 'kyradi-superapp.firebaseapp.com',
    storageBucket: 'kyradi-superapp.firebasestorage.app',
    measurementId: 'G-B7KNNCX27G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaW_CXMEt6HuOBOjlPmtbO1jEA_OfV4fA',
    appId: '1:143197560587:android:ebe8acc91573a6e9108c0e',
    messagingSenderId: '143197560587',
    projectId: 'kyradi-superapp',
    storageBucket: 'kyradi-superapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0HG8wgR7E7LdRSD5gKaTyvK0YhoLboHk',
    appId: '1:143197560587:ios:a47ce1ba08c889a0108c0e',
    messagingSenderId: '143197560587',
    projectId: 'kyradi-superapp',
    storageBucket: 'kyradi-superapp.firebasestorage.app',
    iosClientId: '143197560587-inbditnleo9t3it24lfk49gg4s2v3r7h.apps.googleusercontent.com',
    iosBundleId: 'com.kyradi.kyradi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0HG8wgR7E7LdRSD5gKaTyvK0YhoLboHk',
    appId: '1:143197560587:ios:1af013d2112c865d108c0e',
    messagingSenderId: '143197560587',
    projectId: 'kyradi-superapp',
    storageBucket: 'kyradi-superapp.firebasestorage.app',
    iosClientId: '143197560587-9c6s413uq9pkkhfepdajhtu8971d9ja4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bavulgoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2dUY0t2cGXdV7N0CJowNN4OA-nMwfw-Q',
    appId: '1:143197560587:web:af124345cf807040108c0e',
    messagingSenderId: '143197560587',
    projectId: 'kyradi-superapp',
    authDomain: 'kyradi-superapp.firebaseapp.com',
    storageBucket: 'kyradi-superapp.firebasestorage.app',
    measurementId: 'G-MPF9K0PCPJ',
  );

}